### ISSUE TITLE
Allow the creation of cdl. API or CLI or both? For empty file or including example data?

### ISSUE THREAD

**Issue by davesproson** [FAAM-146/vocal#12]

**Comment by graemenott** [comment]
And possibly the inverse? A potential use case is if an organisation uses separate (even non-python) tools to create/populate their netCDFs but do/can use cdl to set the structure. In this case an empty cdl would probably be more sensible?

**Comment by davesproson** [comment]
> And possibly the inverse? A potential use case is if an organisation uses separate (even non-python) tools to create/populate their netCDFs but do/can use cdl to set the structure. In this case an empty cdl would probably be more sensible?

Creation of cdl from the vocal definitions should be easy, as long as we assume the presence of ncdump.

I'm going to put creation of products from cdl out of scope for now, for two reasons:

1. There is info that vocal uses (e.g. the `meta' groups) that have no equivalent
2. The inverse - vocal doesn't currently support all the features of netCDF which could be described by cdl.

Can revisit this later if there's need/demand.

**Comment by davesproson** [comment]
This has (probably!) been addressed in commit a9c2f. Leaving it open for the time being. Note there's some subtlety in creating empty files regarding how you deal with attributes like `actual_range` which don't really make sense before there's any data!

**Comment by davesproson** [comment]
This is now implemented with `.to_cdl(filename: Optional[str]) -> str` called on a dataset, assuming all of the pydantic models are using a correct netCDF mixin.
